name: Convert Logo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  extract-logo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Clone logoTool
        run: |
          git clone https://github.com/MlgmXyysd/Mtk-Logo-Tool.git

      - name: Extract logo.bin
        run: |
          python Mtk-Logo-Tool/logoTool.py logo.bin output_folder

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extracted-images
          path: output_folder/
          if-no-files-found: error
